version: '3.7'

services:

  sample:
    container_name: beaker-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3838:3000
      - 8888:8888
    environment:
      - CHOKIDAR_USEPOLLING=true